

LexikMailerBundle:
    resource: "@LexikMailerBundle/Resources/config/routing.xml"
    prefix:   /admin

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /admin

app_contact:
    resource: "@AppBundle/Controller/ContactController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
