# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Access:
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        ladr_db_provider:
            entity:
                class: AppBundle:Access
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(login$|resetting|register$)
            anonymous: true

        main:
            pattern:    ^/
            provider: ladr_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

    role_hierarchy:
        ROLE_CLIENT: [ROLE_USER]
        ROLE_ADMIN: [ROLE_CLIENT, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPERADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET]}
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
